[versions]
coroutines = "1.4.3"
diskord = "2.0.0"
kotlinLogging = "2.0.8"
logback = "1.2.3"
kotest = "4.6.0"

[libraries]
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
diskord = { module = "com.jessecorbett:diskord-bot", version.ref = "diskord" }
kotlinLogging = { module = "io.github.microutils:kotlin-logging", version.ref = "kotlinLogging" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
kotest-junitRunner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { group = "io.kotest", name = "kotest-property", version.ref = "kotest" }

[bundles]
logging = ["kotlinLogging", "logback"]
kotest = ["kotest-junitRunner", "kotest-property"]