name: Run detekt

on:
  push:
  pull_request:

jobs:
  detekt:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Run detekt task
        run: ./gradlew --build-cache --no-daemon --info detekt
      - name: Upload SARIF files
        uses: github/codeql-action/upload-sarif@v1
        if: ${{ always() }}
        with:
          sarif_file: .